# Generated by Django 3.1.7 on 2021-03-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='descrption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='projects',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
